# Generated by Django 4.2.11 on 2024-04-24 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variant', models.CharField(max_length=200)),
                ('bhk', models.DecimalField(choices=[(1, 1), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4)], decimal_places=1, default=0, max_digits=2)),
                ('carpet', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('negotiable', models.BooleanField(default=True)),
                ('negotiable_upto', models.IntegerField(default=0)),
                ('last_sold_price', models.IntegerField(default=0)),
                ('Tower', models.CharField(max_length=200)),
                ('no_of_balcony', models.IntegerField(default=0)),
                ('dry_balcony_open', models.BooleanField(default=False)),
                ('vastu_compliant', models.BooleanField(default=True)),
                ('east_west_facing_balcony', models.BooleanField(default=False)),
                ('bonus_points', models.CharField(max_length=500)),
                ('dimensions_room', models.JSONField(default=dict)),
                ('balcony_size', models.CharField(max_length=200)),
                ('master_bedroom_size', models.CharField(max_length=200)),
                ('is_duplex', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('builder', models.CharField(max_length=200)),
                ('land_parcel', models.IntegerField(default=0)),
                ('towers', models.IntegerField(default=0)),
                ('amenities', models.JSONField(default=dict)),
                ('location', models.CharField(choices=[('Hinjewadi1', 'Hinjewadi Phase 1'), ('Hinjewadi2', 'Hinjewadi Phase 2'), ('Hinjewadi3', 'Hinjewadi Phase 3'), ('Punawale', 'Punawale'), ('Tathawade', 'Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Marunji', 'Marunji'), ('Balewadi', 'Balewadi'), ('Baner', 'Baner')], max_length=200)),
                ('location_group', models.CharField(choices=[('Hinjewadi', 'Hinjewadi Phase 1,2,3'), ('Punawale', 'Punawale, Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Marunji', 'Marunji'), ('Baner', 'Baner, Balewadi')], max_length=200)),
                ('possession_builder', models.IntegerField(default=0)),
                ('possession_rera', models.IntegerField(default=0)),
                ('project_link', models.CharField(max_length=200)),
                ('project_mb_link', models.CharField(max_length=200)),
                ('nearby', models.JSONField(default=dict)),
                ('bonus_points', models.JSONField(default=dict)),
                ('open_space', models.IntegerField(default=0)),
                ('is_township', models.BooleanField(default=False)),
                ('maintained_by', models.CharField(choices=[('PCMC', 'PCMC'), ('PMC', 'PMC'), ('PMRDA', 'PMRDA'), ('MIDC', 'MIDC')], max_length=200)),
                ('Hospitals_Nearby', models.CharField(max_length=500)),
                ('Commercial_Nearby', models.CharField(max_length=500)),
                ('Schools_Nearby', models.CharField(max_length=500)),
                ('Colleges_Nearby', models.CharField(max_length=500)),
                ('Nearest_Metro', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_sales_name', models.CharField(max_length=200)),
                ('sales_person_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=200)),
                ('buyer_name', models.CharField(max_length=200)),
                ('visited_on', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.apartment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_sales_name', models.CharField(max_length=200)),
                ('sales_person_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=200)),
                ('buyer_name', models.CharField(max_length=200)),
                ('token_on', models.DateTimeField()),
                ('agreement_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.apartment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.projects')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.projects'),
        ),
    ]
