# Generated by Django 4.2.11 on 2024-04-24 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('builder', models.CharField(max_length=200)),
                ('land_parcel', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('towers', models.IntegerField(default=0, null=True)),
                ('amenities', models.CharField(max_length=1000, null=True)),
                ('location', models.CharField(choices=[('Hinjewadi1', 'Hinjewadi Phase 1'), ('Hinjewadi2', 'Hinjewadi Phase 2'), ('Hinjewadi3', 'Hinjewadi Phase 3'), ('Punawale', 'Punawale'), ('Tathawade', 'Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Marunji', 'Marunji'), ('Balewadi', 'Balewadi'), ('Baner', 'Baner')], max_length=200)),
                ('location_group', models.CharField(choices=[('Hinjewadi', 'Hinjewadi Phase 1,2,3'), ('Punawale', 'Punawale, Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Marunji', 'Marunji'), ('Baner', 'Baner, Balewadi')], max_length=200)),
                ('possession_builder', models.IntegerField(default=0, null=True)),
                ('possession_rera', models.IntegerField(default=0, null=True)),
                ('project_link', models.CharField(max_length=200, null=True)),
                ('project_mb_link', models.CharField(max_length=200, null=True)),
                ('nearby', models.CharField(max_length=1000, null=True)),
                ('bonus_points', models.CharField(max_length=1000, null=True)),
                ('open_space', models.IntegerField(default=0, null=True)),
                ('is_township', models.BooleanField(default=False)),
                ('is_mhada_inside', models.BooleanField(default=False)),
                ('maintained_by', models.CharField(choices=[('PCMC', 'PCMC'), ('PMC', 'PMC'), ('PMRDA', 'PMRDA'), ('MIDC', 'MIDC'), ('Other', 'Other')], max_length=200)),
                ('Hospitals_Nearby', models.CharField(max_length=500, null=True)),
                ('Commercial_Nearby', models.CharField(max_length=500, null=True)),
                ('Schools_Nearby', models.CharField(max_length=500, null=True)),
                ('Colleges_Nearby', models.CharField(max_length=500, null=True)),
                ('Nearest_Metro', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Tower',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Variant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony_size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bonus_points',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='dimensions_room',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='last_sold_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='master_bedroom_size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='negotiable',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='negotiable_upto',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='no_of_balcony',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentsales',
            name='agreement_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='apartmentsales',
            name='pre_sales_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pre_sales_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.project'),
        ),
        migrations.AlterField(
            model_name='apartmentsales',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.project'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.project'),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
