# Generated by Django 4.2.11 on 2024-04-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0002_project_alter_apartment_tower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='Tower',
            field=models.CharField(blank=True, help_text='Tower name or number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Variant',
            field=models.CharField(blank=True, help_text='Variant of Apartment Eg luxury/premium', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony_size',
            field=models.CharField(blank=True, help_text='11 * 5', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bonus_points',
            field=models.CharField(help_text='Eg walking wardrobe, etc', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='carpet',
            field=models.IntegerField(default=0, help_text='carpet area in square feet'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='dimensions_room',
            field=models.CharField(blank=True, help_text='living - 20 * 14, comma separated', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_duplex',
            field=models.BooleanField(default=False, help_text='check the box if apartment is duplex'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='last_sold_price',
            field=models.IntegerField(default=0, help_text='last sold price in lakhs', null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='master_bedroom_size',
            field=models.CharField(blank=True, help_text='15 * 12', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='negotiable_upto',
            field=models.IntegerField(default=0, help_text='negotiable upto in lakhs', null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='no_of_balcony',
            field=models.IntegerField(default=0, help_text='number of balcony; excluding dry balcony', null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(default=0, help_text='price of apartment in lakhs', null=True),
        ),
        migrations.AlterField(
            model_name='apartmentsales',
            name='pre_sales_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Colleges_Nearby',
            field=models.CharField(blank=True, help_text='Colleges nearby, comma separated', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Commercial_Nearby',
            field=models.CharField(blank=True, help_text='Commercial nearby, comma separated', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Hospitals_Nearby',
            field=models.CharField(blank=True, help_text='Hospitals nearby, comma separated', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Nearest_Metro',
            field=models.CharField(blank=True, help_text='Nearest Metro, comma separated', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Schools_Nearby',
            field=models.CharField(blank=True, help_text='Schools nearby, comma separated', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='amenities',
            field=models.CharField(blank=True, help_text='comma separated list of amenities', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bonus_points',
            field=models.CharField(help_text='Eg 200m from metro, 3 minute drive from expressway', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='builder',
            field=models.CharField(help_text='Name of Builder', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_mhada_inside',
            field=models.BooleanField(default=False, help_text='check the box if mhada is inside project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_township',
            field=models.BooleanField(default=False, help_text='check the box if project in township'),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_parcel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Land parcel in acres', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='maintained_by',
            field=models.CharField(choices=[('PCMC', 'PCMC'), ('PMC', 'PMC'), ('PMRDA', 'PMRDA'), ('MIDC', 'MIDC'), ('Other', 'Other')], help_text='maintained by PCMC, PMRDA, etc', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of project', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='nearby',
            field=models.CharField(help_text='nearby places/landmark', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='open_space',
            field=models.IntegerField(default=0, help_text='percentage of open sapce', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_builder',
            field=models.IntegerField(default=0, help_text='Year of Possession as per builder', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_rera',
            field=models.IntegerField(default=0, help_text='Year of Possession as per rera', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.CharField(help_text='official website of project', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_mb_link',
            field=models.CharField(help_text='mbhousing google drive link of project', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='towers',
            field=models.IntegerField(default=0, help_text='Number of towers', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pre_sales_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
