# Generated by Django 4.2.11 on 2024-04-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryTool', '0003_alter_apartment_tower_alter_apartment_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='project',
        ),
        migrations.AddField(
            model_name='visit',
            name='pre_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_sales_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='sales_person',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='sales_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.CharField(blank=True, help_text='official website of project', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_mb_link',
            field=models.CharField(blank=True, help_text='mbhousing google drive link of project', max_length=200, null=True),
        ),
    ]
