# Generated by Django 4.2.11 on 2024-04-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0004_remove_visit_project_visit_pre_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='pre_sales_name',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='sales_person_name',
        ),
    ]
