# Generated by Django 4.2.11 on 2024-04-25 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0005_remove_visit_pre_sales_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 25, 10, 59, 34, 103702)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
