# Generated by Django 4.2.11 on 2024-04-25 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0006_visit_created_on_visit_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.project'),
            preserve_default=False,
        ),
    ]
