# Generated by Django 4.2.11 on 2024-04-25 06:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0007_visit_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='apartment_new',
            field=smart_selects.db_fields.GroupedForeignKey(default=2, group_field='project', on_delete=django.db.models.deletion.CASCADE, related_name='an', to='InventoryTool.apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='InventoryTool.apartment'),
        ),
    ]
