# Generated by Django 4.2.11 on 2024-04-25 07:00

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0008_visit_apartment_new_alter_visit_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='apartment_new',
        ),
        migrations.AlterField(
            model_name='visit',
            name='apartment',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='project', on_delete=django.db.models.deletion.CASCADE, related_name='an', to='InventoryTool.apartment'),
        ),
    ]
