# Generated by Django 4.2.11 on 2024-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0009_remove_visit_apartment_new_alter_visit_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='inventory_finished',
            field=models.BooleanField(default=False, help_text='check the box if apartment has no inventory left'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='jodi_unit_available',
            field=models.BooleanField(default=False, help_text='check the box if apartment has jodi unit option'),
        ),
        migrations.AddField(
            model_name='project',
            name='construction',
            field=models.CharField(choices=[('Mivan', 'Mivan'), ('Bricks', 'Bricks'), ('Hybrid', 'Internal Bricks Outer Mivan')], default='Mivan', help_text='contruction type- Mivan, bricks, hybrid', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('Hinjewadi1', 'Hinjewadi Phase 1'), ('Hinjewadi2', 'Hinjewadi Phase 2'), ('Hinjewadi3', 'Hinjewadi Phase 3'), ('Punawale', 'Punawale'), ('Tathawade', 'Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Marunji / Hinjewadi', 'Hinjewadi / Marunji'), ('Balewadi', 'Balewadi'), ('Baner', 'Baner'), ('Mahalunge', 'Mahalunge')], max_length=200),
        ),
    ]
