# Generated by Django 4.2.11 on 2024-04-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0010_apartment_inventory_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='conversation_description',
            field=models.TextField(blank=True, help_text='A brief description about the conversation you had with the customers'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bonus_points',
            field=models.CharField(blank=True, default='NA', help_text='Eg 200m from metro, 3 minute drive from expressway', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('Hinjewadi1', 'Hinjewadi Phase 1'), ('Hinjewadi2', 'Hinjewadi Phase 2'), ('Hinjewadi3', 'Hinjewadi Phase 3'), ('Punawale', 'Punawale'), ('Tathawade', 'Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Hinjewadi / Marunji', 'Hinjewadi / Marunji'), ('Balewadi', 'Balewadi'), ('Baner', 'Baner'), ('Mahalunge', 'Mahalunge')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='nearby',
            field=models.CharField(blank=True, default='NA', help_text='nearby places/landmark', max_length=1000),
            preserve_default=False,
        ),
    ]
