# Generated by Django 4.2.11 on 2024-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0011_visit_conversation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='builder_sales_person',
            field=models.CharField(default='NA', help_text='builder_sales_person', max_length=200),
            preserve_default=False,
        ),
    ]
