# Generated by Django 4.2.11 on 2024-04-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0012_visit_builder_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='balcony_facing',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], help_text='balcony facing East, West. North, South', max_length=100, null=True),
        ),
    ]
