# Generated by Django 4.2.11 on 2024-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0013_apartment_balcony_facing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='balcony_facing',
            field=models.CharField(blank=True, help_text='balcony facing East, West. North, South', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bonus_points',
            field=models.TextField(help_text='Eg walking wardrobe, etc', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='dimensions_room',
            field=models.TextField(blank=True, help_text='living - 20 * 14, comma separated', max_length=1000, null=True),
        ),
    ]
