# Generated by Django 4.2.11 on 2024-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0014_alter_apartment_balcony_facing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='no_of_lifts',
            field=models.IntegerField(default=0, help_text='number of lifts including service', null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='per_floor_flats',
            field=models.IntegerField(default=0, help_text='number of flats per floor', null=True),
        ),
    ]
