# Generated by Django 4.2.11 on 2024-04-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0015_apartment_no_of_lifts_apartment_per_floor_flats'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_of_lifts',
            field=models.IntegerField(default=0, help_text='number of lifts including service', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='per_floor_flats',
            field=models.IntegerField(default=0, help_text='number of flats per floor', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_builder',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], default=0, help_text='Year of Possession as per builder', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_rera',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], default=0, help_text='Year of Possession as per rera', null=True),
        ),
    ]
