# Generated by Django 4.2.11 on 2024-04-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0016_project_no_of_lifts_project_per_floor_flats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='no_of_lifts',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='per_floor_flats',
        ),
    ]
