# Generated by Django 4.2.11 on 2024-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0017_remove_apartment_no_of_lifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='inventory_availability_comments',
            field=models.TextField(blank=True, help_text='inventory availability comments', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='inventory_enquiry_date',
            field=models.DateField(blank=True, help_text='date of inventory enquiry', null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='no_of_inventory_available',
            field=models.IntegerField(default=-1, help_text='number of inventory available', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='about_builder',
            field=models.TextField(blank=True, help_text='About Builder Legacy, previous apartment delivered, etc', max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='no_of_floors',
            field=models.IntegerField(default=-1, help_text='number of floors', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='no_of_units',
            field=models.IntegerField(default=-1, help_text='number of units', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='possesion_date_builder',
            field=models.DateField(blank=True, help_text='Date of possession by builder', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='possesion_date_misc',
            field=models.TextField(blank=True, help_text='Date of possession misc notes'),
        ),
        migrations.AddField(
            model_name='project',
            name='possesion_date_rera',
            field=models.DateField(blank=True, help_text='Date of possession as per rera', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bonus_points',
            field=models.TextField(blank=True, help_text='Eg 200m from metro, 3 minute drive from expressway', max_length=1000),
        ),
    ]
