# Generated by Django 4.2.11 on 2024-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0018_apartment_inventory_availability_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='master_bedroom_with_balcony',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('May', 'May'), ('NA', 'NA')], default='NA', help_text='master bedroom with balcony'),
        ),
    ]
