# Generated by Django 4.2.11 on 2024-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0019_apartment_master_bedroom_with_balcony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='inventory_enquiry_date',
            field=models.DateTimeField(auto_now=True, help_text='date of inventory enquiry', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possesion_date_builder',
            field=models.DateTimeField(blank=True, help_text='Date of possession by builder', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possesion_date_rera',
            field=models.DateTimeField(blank=True, help_text='Date of possession as per rera', null=True),
        ),
    ]
