# Generated by Django 4.2.11 on 2024-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0020_alter_apartment_inventory_enquiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='possesion_date_builder',
            field=models.DateField(blank=True, help_text='Date of possession by builder', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possesion_date_rera',
            field=models.DateField(blank=True, help_text='Date of possession as per rera', null=True),
        ),
    ]
