# Generated by Django 4.2.11 on 2024-04-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0021_alter_project_possesion_date_builder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='carpet_variants',
            field=models.CharField(blank=True, help_text='carpet variants comma separated Eg- 720, 722, 754', max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='builder_sales_person_phone',
            field=models.CharField(default='NA', help_text='builder_sales_person_phone', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='buyer_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Variant',
            field=models.CharField(blank=True, help_text='Variant of Apartment Eg comfort/luxury/premium/Royal', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possesion_date_builder',
            field=models.DateField(blank=True, help_text='Date of possession by builder, Add Date as 1 Eg 1 Dec', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possesion_date_rera',
            field=models.DateField(blank=True, help_text='Date of possession as per rera, Add Date as 1 Eg 1 Dec', null=True),
        ),
    ]
