# Generated by Django 4.2.11 on 2024-05-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0022_apartment_carpet_variants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negatives', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.apartment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryTool.project')),
            ],
        ),
    ]
