# Generated by Django 4.2.11 on 2024-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0023_negatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='no_of_sites_visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_group',
            field=models.CharField(choices=[('Hinjewadi', 'Hinjewadi Phase 1,2,3, Marunji'), ('Punawale', 'Punawale, Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Baner', 'Baner, Balewadi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='maintained_by',
            field=models.CharField(choices=[('PCMC', 'PCMC'), ('PMC', 'PMC'), ('PMRDA', 'PMRDA'), ('MIDC', 'MIDC'), ('Township', 'Township'), ('Other', 'Other')], help_text='maintained by PCMC, PMRDA, etc', max_length=200),
        ),
    ]
