# Generated by Django 4.2.11 on 2024-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0024_visit_no_of_sites_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
