# Generated by Django 4.2.11 on 2024-05-09 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryTool', '0026_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('client_budget', models.IntegerField(blank=True, help_text='client budget in lakhs. 1 crore = 100 lakh', null=True)),
                ('client_location', models.CharField(blank=True, max_length=200, null=True)),
                ('client_job_location', models.CharField(blank=True, max_length=200, null=True)),
                ('other_property_visited', models.CharField(blank=True, max_length=200, null=True)),
                ('any_other_details', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_followup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
