# Generated by Django 4.2.11 on 2024-05-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0027_dailyfollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfollowup',
            name='any_other_details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
