# Generated by Django 4.2.11 on 2024-05-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0028_alter_dailyfollowup_any_other_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='direction',
            field=models.TextField(blank=True, help_text='customer puchta h project kaha h ?'),
        ),
    ]
