# Generated by Django 4.2.11 on 2024-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0029_project_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfollowup',
            name='bhk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
