# Generated by Django 4.2.11 on 2024-05-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0030_dailyfollowup_bhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rating',
            field=models.IntegerField(default=5, help_text='rating to show good rated apartments first'),
        ),
        migrations.AlterField(
            model_name='dailyfollowup',
            name='bhk',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4)], max_length=200, null=True),
        ),
    ]
