# Generated by Django 4.2.11 on 2024-05-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0031_apartment_rating_alter_dailyfollowup_bhk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfollowup',
            name='bhk',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4)], decimal_places=1, max_digits=2, max_length=200, null=True),
        ),
    ]
