# Generated by Django 4.2.11 on 2024-05-16 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0032_alter_dailyfollowup_bhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfollowup',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='visit',
            name='buyer_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='add amount in lakhs', max_digits=6, null=True),
        ),
    ]
