# Generated by Django 4.2.11 on 2024-05-16 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0033_dailyfollowup_date_alter_visit_buyer_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfollowup',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
