# Generated by Django 4.2.11 on 2024-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0034_alter_dailyfollowup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='litigation',
            field=models.BooleanField(default=False, help_text='check the box if the project has litigation'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bhk',
            field=models.DecimalField(choices=[(1.0, 1.0), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dailyfollowup',
            name='bhk',
            field=models.DecimalField(choices=[(1.0, 1.0), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=2, max_length=200, null=True),
        ),
    ]
