# Generated by Django 4.2.11 on 2024-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0035_project_litigation_alter_apartment_bhk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyfollowup',
            name='any_other_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction',
            field=models.CharField(choices=[('Mivan', 'Mivan'), ('Bricks', 'Bricks'), ('Hybrid', 'Internal Bricks Outer Mivan'), ('RCC', 'RCC Blocks')], help_text='contruction type- Mivan, bricks, hybrid', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('Hinjewadi1', 'Hinjewadi Phase 1'), ('Hinjewadi2', 'Hinjewadi Phase 2'), ('Hinjewadi3', 'Hinjewadi Phase 3'), ('Wakad', 'Wakad'), ('Tathawade', 'Tathawade'), ('Punawale', 'Punawale'), ('Hinjewadi / Marunji', 'Hinjewadi / Marunji'), ('Balewadi', 'Balewadi'), ('Baner', 'Baner'), ('Mahalunge', 'Mahalunge'), ('Ravet', 'Ravet')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_group',
            field=models.CharField(choices=[('Hinjewadi', 'Hinjewadi Phase 1,2,3, Marunji'), ('Punawale', 'Punawale, Tathawade'), ('Wakad', 'Wakad'), ('Ravet', 'Ravet'), ('Baner', 'Baner, Balewadi'), ('Mahalunge', 'Mahalunge')], max_length=200),
        ),
    ]
