# Generated by Django 4.2.11 on 2024-06-04 07:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0036_attendance_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfollowup',
            old_name='any_other_details',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='dailyfollowup',
            name='client_location',
        ),
        migrations.AddField(
            model_name='dailyfollowup',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Hinjewadi1', 'Hinjewadi Phase 1'), ('Hinjewadi2', 'Hinjewadi Phase 2'), ('Hinjewadi3', 'Hinjewadi Phase 3'), ('Wakad', 'Wakad'), ('Tathawade', 'Tathawade'), ('Punawale', 'Punawale'), ('Hinjewadi / Marunji', 'Hinjewadi / Marunji'), ('Balewadi', 'Balewadi'), ('Baner', 'Baner'), ('Mahalunge', 'Mahalunge'), ('Ravet', 'Ravet')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyfollowup',
            name='other_property_visited',
            field=models.CharField(blank=True, help_text='properties visited with other cp', max_length=200, null=True),
        ),
    ]
