# Generated by Django 4.2.11 on 2024-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0037_rename_any_other_details_dailyfollowup_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfollowup',
            name='client_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=8, help_text='client budget in lakhs. 1 crore = 100 lakh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bonus_points',
            field=models.TextField(blank=True, help_text='Eg walking wardrobe, etc', max_length=1000, null=True),
        ),
    ]
