# Generated by Django 4.2.11 on 2024-06-16 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryTool', '0038_dailyfollowup_client_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=200)),
                ('client_details', models.TextField(blank=True, max_length=2000, null=True)),
                ('hike_call_expectation', models.TextField(blank=True, max_length=2000, null=True)),
                ('hike_call_followup', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_hike_call', to=settings.AUTH_USER_MODEL)),
                ('hike_call_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_hike_call_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
