# Generated by Django 4.2.11 on 2024-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0039_hikecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikecall',
            name='client_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
