# Generated by Django 4.2.11 on 2024-06-16 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryTool', '0040_hikecall_client_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyFollowUp',
            new_name='DailyPotentialClients',
        ),
    ]
