# Generated by Django 4.2.11 on 2024-06-23 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryTool', '0041_rename_dailyfollowup_dailypotentialclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_phone', models.CharField(max_length=200)),
                ('buyer_name', models.CharField(max_length=200)),
                ('builder_sales_person', models.CharField(help_text='builder_sales_person_new_visit', max_length=200)),
                ('builder_sales_person_phone', models.CharField(help_text='builder_sales_person_phone_new_visit', max_length=200)),
                ('buyer_budget', models.IntegerField(default=0, help_text='add amount in lakhs', null=True)),
                ('visited_on', models.DateField(default=datetime.date.today)),
                ('no_of_sites_visited', models.IntegerField(default=0)),
                ('conversation_description', models.TextField(blank=True, help_text='A brief description about the conversation you had with the customers')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pre_sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_sales_person_new_visit', to=settings.AUTH_USER_MODEL)),
                ('project_visited', models.ManyToManyField(to='InventoryTool.apartment')),
                ('sales_person', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='sales_person_new_visit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
