# Generated by Django 4.2.11 on 2024-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0042_newvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvisit',
            name='rating',
            field=models.CharField(choices=[('very hot', 'Very Hot'), ('hot', 'hot'), ('exploring', 'Exploring'), ('cold', 'cold'), ('very cold', 'Very Cold')], default='exploring', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newvisit',
            name='visit_is_revisit',
            field=models.BooleanField(default=False, help_text='check the box if the project has litigation'),
        ),
    ]
