# Generated by Django 4.2.11 on 2024-06-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0043_newvisit_rating_newvisit_visit_is_revisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypotentialclients',
            name='rating',
            field=models.CharField(choices=[('very hot', 'Very Hot'), ('hot', 'Hot'), ('exploring', 'Exploring'), ('cold', 'Cold'), ('very cold', 'Very Cold')], default='exploring', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='buyer_budget',
            field=models.IntegerField(default=0, help_text='add amount in lakhs. if budget = `1.2 cr` add `120`', null=True),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='project_visited',
            field=models.ManyToManyField(help_text='select all the projects', to='InventoryTool.apartment'),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='rating',
            field=models.CharField(choices=[('very hot', 'Very Hot'), ('hot', 'Hot'), ('exploring', 'Exploring'), ('cold', 'Cold'), ('very cold', 'Very Cold')], max_length=200),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='visit_is_revisit',
            field=models.BooleanField(default=False, help_text='check the box if the visit is revisit'),
        ),
    ]
