# Generated by Django 4.2.11 on 2024-06-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0044_dailypotentialclients_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypotentialclients',
            name='client_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='client budget in lakhs. 1 crore = 100 lakh', null=True),
        ),
        migrations.AlterField(
            model_name='dailypotentialclients',
            name='rating',
            field=models.CharField(choices=[('very hot', 'Very Hot'), ('hot', 'Hot'), ('exploring', 'Exploring'), ('cold', 'Cold'), ('very cold', 'Very Cold')], max_length=200, null=True),
        ),
    ]
