# Generated by Django 4.2.11 on 2024-06-30 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryTool', '0045_alter_dailypotentialclients_client_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_phone', models.CharField(max_length=200)),
                ('buyer_name', models.CharField(max_length=200)),
                ('follow_up_date', models.DateField(default=datetime.date.today)),
                ('details', models.TextField(blank=True, help_text='any other details')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='newvisit',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_new_visit', to=settings.AUTH_USER_MODEL),
        ),
    ]
