# Generated by Django 4.2.11 on 2024-06-30 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryTool', '0046_delayedfollowup_newvisit_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvisit',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_new_visit', to=settings.AUTH_USER_MODEL),
        ),
    ]
