# Generated by Django 6.0.5 on 2026-05-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTool', '0047_alter_newvisit_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentsales',
            options={'verbose_name': 'Apartment Sales', 'verbose_name_plural': 'Apartment Sales'},
        ),
        migrations.AlterModelOptions(
            name='negatives',
            options={'verbose_name': 'Negative', 'verbose_name_plural': 'Negatives'},
        ),
    ]
